---
title: "Fantasy Football"
author: "Christian Thieme"
date: "5/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fantasy Football Model

```{r message=FALSE, warning=FALSE}
library(tidymodels)
library(readr)
library(glmnet)
library(ranger)
library(vip)
library(tidyverse)
library(caret)
library(imputeTS)
library(janitor)
library(tidyr)
```


```{r message=FALSE, warning=FALSE}
fb <- 
  readr::read_csv("C:/Users/Chris/OneDrive/Personal R Projects/FantasyFootballModel/football2.csv") %>% 
  mutate_if(is.character, as.factor) %>%
  mutate(Combine_Vertical = as.numeric(Combine_Vertical))
  

dim(fb)
```

```{r}
('School', 'Conference', 'DR', 'DP', 'DraftAge', 'GamesPlayed_20', 'Receptions_20', 'ReceivingYards_20', 'ReceivingTDs_20', 'MSReceptions_20', 'MSReceivingYards_20',
'CombinedRECMS_20', 'TotalCombinedMS_20', 'Yards_Reception_20', 'Yards_ReceptionOverTMAverage_20', 'REC_TMPassAttempts_20', 'Yards_TMPassAttempts_20', 'Touches_20', 
'ScrimmageYards_20', 'ScrimmageYards_Play_20', 'TotalTouches_20', 'TotalYards_20', 'TotalCareer_REC', 'TotalCareer_REC_GP', 'TotalCareer_RECYards', 'TotalCareer_RECYards_GP', 'TotalCareer_RECTDs', 'TotalCareer_RECTDs_GP', 'TotalCareer_Yards_REC', 'TotalCareer_Touches', 'TotalCareer_Touches_GP', 'TotalCareer_PPRPoints', 'TotalCareer_PPR_GP', 'TotalCareer_PPR_Touch', 'TotalCareer_TotalTouches_GP', 'TotalCareer_TotalYards', 'TotalCareer_TotalYards_GP', 'TotalCareer_TotalTDs', 'TotalCareer_TotalTDs_GP', 'CareerBest_REC', 'CareerBest_RECs_GP', 'CareerBest_RECYards', 'CareerBest_RECYards_GP', 'CareerBest_RECTD', 'CareerBest_RECTDs_GP', 'CareerBest_RECMS', 'CareerBest_RECYardsMS', 'CareerBest_RECTDsMS', 'CareerBest_CombinedRECMS', 'CareerBest_TotalMS', 'CareerBest_Yards_REC', 'CareerBest_YDs_RECOverTMAVG', 'CareerBest_REC_TMPA', 'CareerBest_RECYards_TMPA', 'CareerBest_RECTDS_TMPA', 'CareerBest_Touches', 'CareerBest_Touches_GP',          'CareerBest_SCRIMYards', 'CareerBest_SCRIMYards_GP', 'CareerBest_SCRIMTDs', 'CareerBest_SCRIMTDs_GP', 'CareerBest_TouchMS', 'CareerBest_SCRIMYardsMS',                'CareerBest_SCRIMTDsMS', 'CareerBest_COMBSCRIMMS',  'CareerBest_SCRIMYards_Touch',  'CareerBest_SCRIMYDs_TouchOverTMAVG', 'CareerBest_Touch_Play',        'CareerBest_SCRIMYards_Play', 'CareerBest_SCRIMTDs_Play', 'CareerBest_PPRPoints', 'CareerBest_PPR_GP', 'CareerBest_PPR_Touch', 'CareerBest_TotalTouches',            'CareerBest_TotalTouches_GP', 'CareerBest_TotalYards', 'CareerBest_TotalYards_GP', 'CareerBest_TotalTDs',  'CareerBest_TotalTDs_GP', 'CareerLast_RECs_GP',               'CareerLast_RECYards', 'CareerLast_RECYards_GP', 'CareerLast_RECTDs', 'CareerLast_RECTDs_GP', 'CareerLast_RECMS', 'CareerLast_RECYardsMS',                 'CareerLast_RECTDsMS', 'CareerLast_CombinedRECMS', 'CareerLast_TotalMS', 'CareerLast_Yards_REC', 'CareerLast_YDs_RECOverTMAVG', 'CareerLast_REC_TMPA',             'CareerLast_RECYards_TMPA', 'CareerLast_RECTDS_TMPA', 'CareerLast_Touches', 'CareerLast_Touches_GP', 'CareerLast_SCRIMYards', 'CareerLast_SCRIMYards_GP',                 'CareerLast_SCRIMTDs', 'CareerLast_TotalTouches_GP', 'CareerLast_TotalYards', 'CareerLast_TotalYards_GP', 'CareerLast_TotalTDs', 'CareerAverage_RECYards',             'CareerAverage_RECYards_GP', 'CareerAverage_RECTDs', 'CareerAverage_RECTDs_GP', 'CareerAverage_RECMS', 'CareerAverage_RECYardsMS', 'CareerAverage_RECTDsMS',            'CareerAverage_CombinedRECMS', 'CareerAverage_TotalMS', 'CareerAverage_Yards_REC', 'CareerAverage_YDs_RECOverTMAVG', 'CareerAverage_REC_TMPA', 
'CareerAverage_RECYards_TMPA', 'CareerAverage_RECTDS_TMPA', 'CareerAverage_Touches', 'CareerAverage_Touches_GP', 'CareerAverage_SCRIMYards',      'CareerAverage_SCRIMYards_GP','CareerAverage_SCRIMTDs', 'CareerAverage_SCRIMTDs_GP', 'CareerAverage_TouchMS', 'CareerAverage_SCRIMYardsMS', 'CareerAverage_SCRIMTDsMS'  'CareerAverage_COMBSCRIMMS', 'CareerAverage_SCRIMYards_Touch', 'CareerAverage_SCRIMYDs_TouchOverTMAVG', 'CareerAverage_Touch_Play', 'CareerAverage_SCRIMYards_Play',
'CareerAverage_SCRIMTDs_Play', 'CareerAverage_PPRPoints', 'CareerAverage_PPR_GP', 'CareerAverage_PPR_Touch', 'CareerAverage_TotalTouches', 'CareerAverage_TotalTouches_GP', 'CareerAverage_TotalYards', 'CareerAverage_TotalYards_GP', 'CareerAverage_TotalTDs', 'CareerAverage_TotalTDs_GP', 'CollegeDominator_RUSHCD', 'CollegeDominator_RECCD', 'CollegeDominator_SCRIMCD', 'Combine_BMI', 'Combine_Height', 'Combine_Weight', 'Combine_HaSS', 'B_O', 'PPG')


 
```

```{r}
names(fb)
```

```{r}
colSums(is.na(fb)) 
```

```{r}
ffb <- fb %>% select('School', 'Conference', 'DR', 'DP', 'DraftAge',  'TotalCareer_REC', 'GamesPlayed_20', 'Receptions_20', 'ReceivingYards_20', 'MSReceptions_20', 'MSReceivingYards_20','CombinedRECMS_20', 'TotalCombinedMS_20', 'Yards_Reception_20', 'Yards_ReceptionOverTMAverage_20', 'REC_TMPassAttempts_20', 'Yards_TMPassAttempts_20', 'Touches_20', 'ScrimmageYards_20', 'ScrimmageYards_Play_20', 'TotalTouches_20', 'TotalYards_20','TotalCareer_REC_GP', 'TotalCareer_RECYards', 'TotalCareer_RECYards_GP', 'TotalCareer_RECTDs', 'TotalCareer_RECTDs_GP', 'TotalCareer_Yards_REC', 'TotalCareer_Touches', 'TotalCareer_Touches_GP', 'TotalCareer_PPRPoints', 'TotalCareer_PPR_GP', 'TotalCareer_PPR_Touch', 'TotalCareer_TotalTouches_GP', 'TotalCareer_TotalYards', 'TotalCareer_TotalYards_GP', 'TotalCareer_TotalTDs', 'TotalCareer_TotalTDs_GP', 'CareerBest_REC', 'CareerBest_RECs_GP', 'CareerBest_RECYards', 'CareerBest_RECYards_GP', 'CareerBest_RECTDs', 'CareerBest_RECTDs_GP', 'CareerBest_RECMS', 'CareerBest_RECYardsMS', 'CareerBest_RECTDsMS', 'CareerBest_CombinedRECMS', 'CareerBest_TotalMS', 'CareerBest_Yards_REC', 'CareerBest_YDs_RECOverTMAVG', 'CareerBest_REC_TMPA', 'CareerBest_RECYards_TMPA', 'CareerBest_RECTDS_TMPA', 'CareerBest_Touches', 'CareerBest_Touches_GP', 'CareerBest_SCRIMYards', 'CareerBest_SCRIMYards_GP', 'CareerBest_SCRIMTDs', 'CareerBest_SCRIMTDs_GP', 'CareerBest_TouchMS', 'CareerBest_SCRIMYardsMS', 'CareerBest_SCRIMTDsMS', 'CareerBest_COMBSCRIMMS',  'CareerBest_SCRIMYards_Touch',  'CareerBest_SCRIMYDs_TouchOverTMAVG', 'CareerBest_Touch_Play', 'CareerBest_SCRIMYards_Play', 'CareerBest_SCRIMTDs_Play', 'CareerBest_PPRPoints', 'CareerBest_PPR_GP', 'CareerBest_PPR_Touch', 'CareerBest_TotalTouches',  'CareerBest_TotalTouches_GP', 'CareerBest_TotalYards', 'CareerBest_TotalYards_GP', 'CareerBest_TotalTDs',  'CareerBest_TotalTDs_GP', 'CareerLast_RECs_GP', 'CareerLast_RECYards', 'CareerLast_RECYards_GP', 'CareerLast_RECTDs', 'CareerLast_RECTDs_GP', 'CareerLast_RECMS', 'CareerLast_RECYardsMS',                 'CareerLast_RECTDsMS', 'CareerLast_CombinedRECMS', 'CareerLast_TotalMS', 'CareerLast_Yards_REC', 'CareerLast_YDs_RECOverTMAVG', 'CareerLast_REC_TMPA',             'CareerLast_RECYards_TMPA', 'CareerLast_RECTDS_TMPA', 'CareerLast_Touches', 'CareerLast_Touches_GP', 'CareerLast_SCRIMYards', 'CareerLast_SCRIMYards_GP',                 'CareerLast_SCRIMTDs', 'CareerLast_TotalTouches_GP', 'CareerLast_TotalYards', 'CareerLast_TotalYards_GP', 'CareerLast_TotalTDs', 'CareerAverage_RECYards',             'CareerAverage_RECYards_GP', 'CareerAverage_RECTDs', 'CareerAverage_RECTDs_GP', 'CareerAverage_RECMS', 'CareerAverage_RECYardsMS', 'CareerAverage_RECTDsMS',            'CareerAverage_CombinedRECMS', 'CareerAverage_TotalMS', 'CareerAverage_Yards_REC', 'CareerAverage_YDs_RECOverTMAVG', 'CareerAverage_REC_TMPA', 
'CareerAverage_RECYards_TMPA', 'CareerAverage_RECTDS_TMPA', 'CareerAverage_Touches', 'CareerAverage_Touches_GP', 'CareerAverage_SCRIMYards',      'CareerAverage_SCRIMYards_GP','CareerAverage_SCRIMTDs', 'CareerAverage_SCRIMTDs_GP', 'CareerAverage_TouchMS', 'CareerAverage_SCRIMYardsMS', 'CareerAverage_SCRIMTDsMS',  'CareerAverage_COMBSCRIMMS', 'CareerAverage_SCRIMYards_Touch', 'CareerAverage_SCRIMYDs_TouchOverTMAVG', 'CareerAverage_Touch_Play', 'CareerAverage_SCRIMYards_Play',
'CareerAverage_SCRIMTDs_Play', 'CareerAverage_PPRPoints', 'CareerAverage_PPR_GP', 'CareerAverage_PPR_Touch', 'CareerAverage_TotalTouches', 'CareerAverage_TotalTouches_GP', 'CareerAverage_TotalYards', 'CareerAverage_TotalYards_GP', 'CareerAverage_TotalTDs', 'CareerAverage_TotalTDs_GP', 'CollegeDominator_RECCD', 'CollegeDominator_SCRIMCD', 'Combine_BMI', 'Combine_Height', 'Combine_Weight', 'Combine_HaSS', 'B_O', 'PPG') %>% janitor::clean_names()


#'GamesPlayed_20', 'Receptions_20', 'ReceivingYards_20', 'MSReceptions_20', 'MSReceivingYards_20','CombinedRECMS_20', 'TotalCombinedMS_20', 'Yards_Reception_20', 'Yards_ReceptionOverTMAverage_20', 'REC_TMPassAttempts_20', 'Yards_TMPassAttempts_20', 'Touches_20', 'ScrimmageYards_20', 'ScrimmageYards_Play_20', 'TotalTouches_20', 'TotalYards_20',
```

```{r}
ffb <- ffb %>%   
  filter(dr < 10) %>%
  filter(ppg != 0) %>% 
  filter(!is.na(ppg))
```


```{r}
ffb %>% count(b_o)
```

Imputing missing values for Combine_HaSS

```{r}
ffb <- ffb %>% 
  mutate(combine_ha_ss = replace_na(combine_ha_ss, median(combine_ha_ss, na.rm = TRUE)))
```


```{r}
ffb <- ffb %>%
  drop_na()
```


```{r}
colSums(is.na(ffb))
```




```{r}
ffb %>% count(b_o)
```

```{r}
colnames(ffb) <- paste("x", colnames(ffb), sep = "_")
```


```{r}
glimpse(ffb)
```

```{r}
ggplot(ffb) + 
  aes(x = x_dp, y = x_ppg, color = x_b_o) + 
  geom_point() +
  labs(title = "draft pick")
```

Remove draft rount of 10 and anyone with ppg of 0.

```{r}
ggplot(ffb) + 
  aes(x = x_dr, y = x_ppg, color = x_b_o) + 
  geom_point()  +
  labs(title = "draft round")
```

```{r}
ggplot(ffb) + 
  aes(x = x_draft_age, y = x_ppg, color = x_b_o) + 
  geom_point()  +
  labs(title = "draft age")
```

```{r}
ggplot(ffb) + 
  aes(x = x_career_best_rec, y = x_ppg, color = x_b_o) + 
  geom_point()  +
  labs(title = "career best rec")
```

Not a strong relationship here. 

```{r}
ggplot(ffb) + 
  aes(x = x_combine_hand_size, y = x_ppg, color = x_b_o) + 
  geom_point()  +
  xlim(8,12) +
  labs(title = "hand size")
```

```{r}
cor_fb <- ffb %>% select(-x_b_o) 
glimpse(cor_fb)
```

```{r}
correlation <- round(cor(cor_fb),2)
```

```{r}
library(reshape2)
melted_cor <- melt(correlation)
head(melted_cor)
```

```{r fig.height=25, fig.width=25}
ggplot(data = melted_cor) +
  aes(x = Var1, y = Var2, fill = value) + 
  geom_tile() +
 geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
    size = 12, hjust = 1))
```


```{r}
cor(ffb$x_ppg, ffb$x_college_dominator_reccd)
```

```{r}
cols <-names(ffb)
col_names <- trimws(cols)
 # make.names(names(fb1))
col_names[make.names(cols) != col_names]
```

```{r}
ffb <- ffb %>% select(-x_ppg)
```


```{r}
ffb %>%
  count(x_b_o) %>%
  mutate(prop = n/sum(n))
```

```{r}
set.seed(123)

splits <- initial_split(ffb, strata = x_b_o, prop = 0.80)

fb_other <- training(splits)
fb_test <- testing(splits)

fb_other %>%
  count(x_b_o) %>%
  mutate(prop = n/sum(n))

fb_test %>%
  count(x_b_o) %>%
  mutate(prop = n/sum(n))
```

```{r}
set.seed(234)

val_set <- validation_split(fb_other, 
                            strata = x_b_o, 
                            prop = 0.80)

val_set# $splits[[1]][[1]] %>% select(B_O) %>% count(B_O)
```

Model: 

```{r}
cores <- parallel::detectCores()
cores
```


```{r}
rf_mod <- 
  rand_forest(mtry = tune(), 
              min_n = tune(), 
              trees = 1500) %>%
  set_engine("ranger", num.threads = cores) %>%
  set_mode("classification")

rf_mod
```

Recipe: Don't need a recipe for RF

```{r}
rf_recipe <- 
 recipe(x_b_o ~ ., data = fb_other) %>%
    step_dummy(all_nominal(), -all_outcomes()) %>%
    step_zv(all_predictors()) %>% #remove all variables with only a single value
    step_normalize(all_predictors())
```

Create a Workflow:

```{r}
rf_workflow <- 
  workflow() %>%
  add_model(rf_mod) %>%
  add_recipe(rf_recipe)
```

Train and Tune the Model

```{r}
rf_res <- 
  rf_workflow %>%
  tune_grid(val_set, 
    grid = 25, 
   # split_rule = "gini",
    control = control_grid(save_pred =TRUE), 
    metrics = metric_set(roc_auc)
  )

rf_res
```

```{r}
rf_res$.notes
```


```{r}
rf_res %>% show_best(metric = "roc_auc")
```


```{r}
rf_res %>% 
  collect_metrics()
```

```{r}
autoplot(rf_res)
```

```{r}
rf_best <- 
  rf_res %>%
  select_best(metric = "roc_auc")

rf_best
```

```{r}
last_rf_mod <- 
  rand_forest(mtry = 26, min_n = 12, trees = 1500) %>%
  set_engine("ranger", num.threads = cores) %>%
  set_mode("classification")

last_rf_workflow <- 
  rf_workflow %>%
  update_model(last_rf_mod) 

set.seed(345)
last_rf_fit <- 
  last_rf_workflow %>%
  last_fit(splits)

last_rf_fit
```

```{r}
last_rf_fit %>%
  collect_metrics()
```

```{r}
fb_test %>% 
  recall(truth = x_b_o, .predictions)
```

```{r}
last_rf_fit %>% 
  collect_predictions( ) %>%
  roc_curve(x_b_o, `.pred_No Breakout`) %>% 
  autoplot()
```

```{r}
fitted <- last_rf_fit %>% 
  collect_predictions() 
```

```{r}
table(fitted$x_b_o,fitted$.pred_class)
```

```{r}
recall(fitted$x_b_o,fitted$.pred_class)
```

